# Generated by Django 4.2 on 2023-05-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
